---
- hosts: localhost

  tasks:
  
  - name: Stop the running container
    command: docker stop esjgroupinc3_frontend_reactjs_student-user-app_qa
    ignore_errors: True

  - name: remove the running container
    command: docker rm esjgroupinc3_frontend_reactjs_student-user-app_qa
    ignore_errors: True

  - name: remove the running image
    command: docker rmi esjgroup/esjgroupinc3_frontend_reactjs_student-user-app_qa:latest
    ignore_errors: True

  - name: Create and run container
    command: docker run -d -p 3001:80 --name esjgroupinc3_frontend_reactjs_student-user-app_qa esjgroup/esjgroupinc3_frontend_reactjs_student-user-app_qa
  