// STUDENT USER DASHBOARD DRAWER OPEN TYPE
export const DASHBOARD_DRAWER_OPEN = 'DASHBOARD_DRAWER_OPEN';
// STUDENT USER DASHBOARD MOBILE DRAWER OPEN TYPE
export const DASHBOARD_MOBILE_DRAWER_OPEN = 'DASHBOARD_MOBILE_DRAWER_OPEN';
// STUDENT USER DASHBOARD ADS DRAWER OPEN TYPE
export const DASHBOARD_ADS_DRAWER_OPEN = 'DASHBOARD_ADS_DRAWER_OPEN';
// STUDENT USER DASHBOARD DRAWER CLOSE TYPE
export const DASHBOARD_DRAWER_CLOSE = 'DASHBOARD_DRAWER_CLOSE';
